import type { ThemeFamily } from './types';

// Catppuccin color palette
// https://github.com/catppuccin/catppuccin
// Latte (light): Base #EFF1F5, Mantle #E6E9EF, Crust #DCE0E8
// Mocha (dark):  Base #1E1E2E, Mantle #181825, Crust #11111B
// Accents: Blue #89B4FA/#1E66F5, Green #A6E3A1/#40A02B, Red #F38BA8/#D20F39
//          Mauve #CBA6F7/#8839EF, Peach #FAB387/#FE640B, Yellow #F9E2AF/#DF8E1D

export const catppuccinTheme: ThemeFamily = {
    id: 'catppuccin',
    name: 'Catppuccin',
    light: {
        text: '#4C4F69',
        textDestructive: '#D20F39',
        textSecondary: '#6C6F85',
        textLink: '#1E66F5',
        deleteAction: '#D20F39',
        warningCritical: '#D20F39',
        warning: '#6C6F85',
        success: '#40A02B',
        surface: '#EFF1F5',
        surfaceRipple: 'rgba(76, 79, 105, 0.08)',
        surfacePressed: '#E6E9EF',
        surfaceSelected: '#CCD0DA',
        surfacePressedOverlay: '#CCD0DA',
        surfaceHigh: '#E6E9EF',
        surfaceHighest: '#DCE0E8',
        divider: '#CCD0DA',
        shadow: { color: 'rgba(76, 79, 105, 0.12)', opacity: 0.12 },
        groupped: {
            background: '#E6E9EF',
            chevron: '#8C8FA1',
            sectionTitle: '#6C6F85',
        },
        header: { background: '#EFF1F5', tint: '#4C4F69' },
        switch: {
            track: { active: '#1E66F5', inactive: '#CCD0DA' },
            thumb: { active: '#EFF1F5', inactive: '#6C6F85' },
        },
        fab: { background: '#4C4F69', backgroundPressed: '#5C5F77', icon: '#EFF1F5' },
        radio: { active: '#1E66F5', inactive: '#CCD0DA', dot: '#1E66F5' },
        modal: { border: 'rgba(76, 79, 105, 0.1)' },
        button: {
            primary: { background: '#4C4F69', tint: '#EFF1F5', disabled: '#CCD0DA' },
            secondary: { tint: '#6C6F85' },
        },
        input: { background: '#E6E9EF', text: '#4C4F69', placeholder: '#8C8FA1' },
        box: {
            warning: { background: '#FDF5E6', border: '#DF8E1D', text: '#DF8E1D' },
            error: { background: '#FDE8EC', border: '#D20F39', text: '#D20F39' },
        },
        status: {
            connected: '#40A02B',
            connecting: '#1E66F5',
            disconnected: '#8C8FA1',
            error: '#D20F39',
            default: '#8C8FA1',
        },
        permission: {
            default: '#8C8FA1',
            acceptEdits: '#1E66F5',
            bypass: '#FE640B',
            plan: '#40A02B',
            readOnly: '#8C8FA1',
            safeYolo: '#FE640B',
            yolo: '#D20F39',
        },
        permissionButton: {
            allow: { background: '#40A02B', text: '#EFF1F5' },
            deny: { background: '#D20F39', text: '#EFF1F5' },
            allowAll: { background: '#1E66F5', text: '#EFF1F5' },
            inactive: { background: '#E6E9EF', border: '#CCD0DA', text: '#8C8FA1' },
            selected: { background: '#CCD0DA', border: '#BCC0CC', text: '#4C4F69' },
        },
        diff: {
            outline: '#CCD0DA',
            success: '#40A02B',
            error: '#D20F39',
            addedBg: '#E6F9E6',
            addedBorder: '#40A02B',
            addedText: '#4C4F69',
            removedBg: '#FDE8EC',
            removedBorder: '#D20F39',
            removedText: '#4C4F69',
            contextBg: '#E6E9EF',
            contextText: '#6C6F85',
            lineNumberBg: '#E6E9EF',
            lineNumberText: '#8C8FA1',
            hunkHeaderBg: '#CCD0DA',
            hunkHeaderText: '#1E66F5',
            leadingSpaceDot: '#CCD0DA',
            inlineAddedBg: '#C6EFC6',
            inlineAddedText: '#1A6B1A',
            inlineRemovedBg: '#FCCCD5',
            inlineRemovedText: '#A00A2C',
        },
        userMessageBackground: '#E6E9EF',
        userMessageText: '#4C4F69',
        agentMessageText: '#4C4F69',
        agentEventText: '#6C6F85',
        syntaxKeyword: '#8839EF',
        syntaxString: '#40A02B',
        syntaxComment: '#9CA0B0',
        syntaxNumber: '#FE640B',
        syntaxFunction: '#1E66F5',
        syntaxBracket1: '#D20F39',
        syntaxBracket2: '#DF8E1D',
        syntaxBracket3: '#179299',
        syntaxBracket4: '#EA76CB',
        syntaxBracket5: '#8839EF',
        syntaxDefault: '#4C4F69',
        gitBranchText: '#6C6F85',
        gitFileCountText: '#6C6F85',
        gitAddedText: '#40A02B',
        gitRemovedText: '#D20F39',
        terminal: {
            background: '#DCE0E8',
            prompt: '#40A02B',
            command: '#4C4F69',
            stdout: '#4C4F69',
            stderr: '#FE640B',
            error: '#D20F39',
            emptyOutput: '#9CA0B0',
        },
    },
    dark: {
        text: '#CDD6F4',
        textDestructive: '#F38BA8',
        textSecondary: '#A6ADC8',
        textLink: '#89B4FA',
        deleteAction: '#F38BA8',
        warningCritical: '#F38BA8',
        warning: '#A6ADC8',
        success: '#A6E3A1',
        surface: '#1E1E2E',
        surfaceRipple: 'rgba(205, 214, 244, 0.08)',
        surfacePressed: '#313244',
        surfaceSelected: '#313244',
        surfacePressedOverlay: '#313244',
        surfaceHigh: '#313244',
        surfaceHighest: '#45475A',
        divider: '#45475A',
        shadow: { color: 'rgba(0, 0, 0, 0.3)', opacity: 0.3 },
        groupped: {
            background: '#181825',
            chevron: '#585B70',
            sectionTitle: '#A6ADC8',
        },
        header: { background: '#1E1E2E', tint: '#CDD6F4' },
        switch: {
            track: { active: '#89B4FA', inactive: '#45475A' },
            thumb: { active: '#CDD6F4', inactive: '#6C7086' },
        },
        fab: { background: '#CDD6F4', backgroundPressed: '#BAC2DE', icon: '#1E1E2E' },
        radio: { active: '#89B4FA', inactive: '#45475A', dot: '#89B4FA' },
        modal: { border: 'rgba(205, 214, 244, 0.1)' },
        button: {
            primary: { background: '#313244', tint: '#CDD6F4', disabled: '#45475A' },
            secondary: { tint: '#A6ADC8' },
        },
        input: { background: '#313244', text: '#CDD6F4', placeholder: '#6C7086' },
        box: {
            warning: { background: 'rgba(249, 226, 175, 0.15)', border: '#F9E2AF', text: '#F9E2AF' },
            error: { background: 'rgba(243, 139, 168, 0.15)', border: '#F38BA8', text: '#F38BA8' },
        },
        status: {
            connected: '#A6E3A1',
            connecting: '#CDD6F4',
            disconnected: '#6C7086',
            error: '#F38BA8',
            default: '#6C7086',
        },
        permission: {
            default: '#6C7086',
            acceptEdits: '#89B4FA',
            bypass: '#FAB387',
            plan: '#A6E3A1',
            readOnly: '#6C7086',
            safeYolo: '#FAB387',
            yolo: '#F38BA8',
        },
        permissionButton: {
            allow: { background: '#A6E3A1', text: '#1E1E2E' },
            deny: { background: '#F38BA8', text: '#1E1E2E' },
            allowAll: { background: '#89B4FA', text: '#1E1E2E' },
            inactive: { background: '#313244', border: '#45475A', text: '#6C7086' },
            selected: { background: '#45475A', border: '#585B70', text: '#CDD6F4' },
        },
        diff: {
            outline: '#45475A',
            success: '#A6E3A1',
            error: '#F38BA8',
            addedBg: '#1A3A2A',
            addedBorder: '#A6E3A1',
            addedText: '#CDD6F4',
            removedBg: '#3A1A28',
            removedBorder: '#F38BA8',
            removedText: '#CDD6F4',
            contextBg: '#1E1E2E',
            contextText: '#6C7086',
            lineNumberBg: '#1E1E2E',
            lineNumberText: '#585B70',
            hunkHeaderBg: '#181825',
            hunkHeaderText: '#89B4FA',
            leadingSpaceDot: '#313244',
            inlineAddedBg: '#2A5A3A',
            inlineAddedText: '#A6E3A1',
            inlineRemovedBg: '#5A2A38',
            inlineRemovedText: '#F38BA8',
        },
        userMessageBackground: '#313244',
        userMessageText: '#CDD6F4',
        agentMessageText: '#CDD6F4',
        agentEventText: '#A6ADC8',
        syntaxKeyword: '#CBA6F7',
        syntaxString: '#A6E3A1',
        syntaxComment: '#6C7086',
        syntaxNumber: '#FAB387',
        syntaxFunction: '#89B4FA',
        syntaxBracket1: '#F38BA8',
        syntaxBracket2: '#F9E2AF',
        syntaxBracket3: '#94E2D5',
        syntaxBracket4: '#F5C2E7',
        syntaxBracket5: '#CBA6F7',
        syntaxDefault: '#CDD6F4',
        gitBranchText: '#A6ADC8',
        gitFileCountText: '#A6ADC8',
        gitAddedText: '#A6E3A1',
        gitRemovedText: '#F38BA8',
        terminal: {
            background: '#181825',
            prompt: '#A6E3A1',
            command: '#CDD6F4',
            stdout: '#CDD6F4',
            stderr: '#FAB387',
            error: '#F38BA8',
            emptyOutput: '#6C7086',
        },
    },
};
