import type { ThemeFamily } from './types';

// Nord color palette
// https://www.nordtheme.com/
// Polar Night: #2E3440 #3B4252 #434C5E #4C566A
// Snow Storm:  #D8DEE9 #E5E9F0 #ECEFF4
// Frost:       #8FBCBB #88C0D0 #81A1C1 #5E81AC
// Aurora:      #BF616A #D08770 #EBCB8B #A3BE8C #B48EAD

export const nordTheme: ThemeFamily = {
    id: 'nord',
    name: 'Nord',
    light: {
        text: '#2E3440',
        textDestructive: '#BF616A',
        textSecondary: '#4C566A',
        textLink: '#5E81AC',
        deleteAction: '#BF616A',
        warningCritical: '#BF616A',
        warning: '#4C566A',
        success: '#A3BE8C',
        surface: '#ECEFF4',
        surfaceRipple: 'rgba(46, 52, 64, 0.08)',
        surfacePressed: '#E5E9F0',
        surfaceSelected: '#D8DEE9',
        surfacePressedOverlay: '#D8DEE9',
        surfaceHigh: '#E5E9F0',
        surfaceHighest: '#D8DEE9',
        divider: '#D8DEE9',
        shadow: { color: 'rgba(46, 52, 64, 0.12)', opacity: 0.12 },
        groupped: {
            background: '#E5E9F0',
            chevron: '#4C566A',
            sectionTitle: '#4C566A',
        },
        header: { background: '#ECEFF4', tint: '#2E3440' },
        switch: {
            track: { active: '#5E81AC', inactive: '#D8DEE9' },
            thumb: { active: '#ECEFF4', inactive: '#4C566A' },
        },
        fab: { background: '#3B4252', backgroundPressed: '#434C5E', icon: '#ECEFF4' },
        radio: { active: '#5E81AC', inactive: '#D8DEE9', dot: '#5E81AC' },
        modal: { border: 'rgba(46, 52, 64, 0.1)' },
        button: {
            primary: { background: '#3B4252', tint: '#ECEFF4', disabled: '#D8DEE9' },
            secondary: { tint: '#4C566A' },
        },
        input: { background: '#E5E9F0', text: '#2E3440', placeholder: '#4C566A' },
        box: {
            warning: { background: '#FDF6E3', border: '#EBCB8B', text: '#D08770' },
            error: { background: '#FDE8E8', border: '#BF616A', text: '#BF616A' },
        },
        status: {
            connected: '#A3BE8C',
            connecting: '#5E81AC',
            disconnected: '#4C566A',
            error: '#BF616A',
            default: '#4C566A',
        },
        permission: {
            default: '#4C566A',
            acceptEdits: '#5E81AC',
            bypass: '#D08770',
            plan: '#A3BE8C',
            readOnly: '#4C566A',
            safeYolo: '#D08770',
            yolo: '#BF616A',
        },
        permissionButton: {
            allow: { background: '#A3BE8C', text: '#ECEFF4' },
            deny: { background: '#BF616A', text: '#ECEFF4' },
            allowAll: { background: '#5E81AC', text: '#ECEFF4' },
            inactive: { background: '#E5E9F0', border: '#D8DEE9', text: '#4C566A' },
            selected: { background: '#D8DEE9', border: '#D8DEE9', text: '#2E3440' },
        },
        diff: {
            outline: '#D8DEE9',
            success: '#A3BE8C',
            error: '#BF616A',
            addedBg: '#E8F5E9',
            addedBorder: '#A3BE8C',
            addedText: '#2E3440',
            removedBg: '#FDECEA',
            removedBorder: '#BF616A',
            removedText: '#2E3440',
            contextBg: '#E5E9F0',
            contextText: '#4C566A',
            lineNumberBg: '#E5E9F0',
            lineNumberText: '#4C566A',
            hunkHeaderBg: '#D8DEE9',
            hunkHeaderText: '#5E81AC',
            leadingSpaceDot: '#D8DEE9',
            inlineAddedBg: '#C8E6C9',
            inlineAddedText: '#1B5E20',
            inlineRemovedBg: '#FFCDD2',
            inlineRemovedText: '#B71C1C',
        },
        userMessageBackground: '#E5E9F0',
        userMessageText: '#2E3440',
        agentMessageText: '#2E3440',
        agentEventText: '#4C566A',
        syntaxKeyword: '#5E81AC',
        syntaxString: '#A3BE8C',
        syntaxComment: '#4C566A',
        syntaxNumber: '#B48EAD',
        syntaxFunction: '#88C0D0',
        syntaxBracket1: '#BF616A',
        syntaxBracket2: '#EBCB8B',
        syntaxBracket3: '#81A1C1',
        syntaxBracket4: '#D08770',
        syntaxBracket5: '#B48EAD',
        syntaxDefault: '#3B4252',
        gitBranchText: '#4C566A',
        gitFileCountText: '#4C566A',
        gitAddedText: '#A3BE8C',
        gitRemovedText: '#BF616A',
        terminal: {
            background: '#2E3440',
            prompt: '#A3BE8C',
            command: '#D8DEE9',
            stdout: '#D8DEE9',
            stderr: '#D08770',
            error: '#BF616A',
            emptyOutput: '#4C566A',
        },
    },
    dark: {
        text: '#ECEFF4',
        textDestructive: '#BF616A',
        textSecondary: '#D8DEE9',
        textLink: '#88C0D0',
        deleteAction: '#BF616A',
        warningCritical: '#BF616A',
        warning: '#D8DEE9',
        success: '#A3BE8C',
        surface: '#2E3440',
        surfaceRipple: 'rgba(236, 239, 244, 0.08)',
        surfacePressed: '#3B4252',
        surfaceSelected: '#3B4252',
        surfacePressedOverlay: '#3B4252',
        surfaceHigh: '#3B4252',
        surfaceHighest: '#434C5E',
        divider: '#434C5E',
        shadow: { color: 'rgba(0, 0, 0, 0.3)', opacity: 0.3 },
        groupped: {
            background: '#2E3440',
            chevron: '#4C566A',
            sectionTitle: '#D8DEE9',
        },
        header: { background: '#2E3440', tint: '#ECEFF4' },
        switch: {
            track: { active: '#5E81AC', inactive: '#434C5E' },
            thumb: { active: '#ECEFF4', inactive: '#4C566A' },
        },
        fab: { background: '#ECEFF4', backgroundPressed: '#D8DEE9', icon: '#2E3440' },
        radio: { active: '#88C0D0', inactive: '#434C5E', dot: '#88C0D0' },
        modal: { border: 'rgba(236, 239, 244, 0.1)' },
        button: {
            primary: { background: '#3B4252', tint: '#ECEFF4', disabled: '#434C5E' },
            secondary: { tint: '#D8DEE9' },
        },
        input: { background: '#3B4252', text: '#ECEFF4', placeholder: '#4C566A' },
        box: {
            warning: { background: 'rgba(235, 203, 139, 0.15)', border: '#EBCB8B', text: '#EBCB8B' },
            error: { background: 'rgba(191, 97, 106, 0.15)', border: '#BF616A', text: '#BF616A' },
        },
        status: {
            connected: '#A3BE8C',
            connecting: '#ECEFF4',
            disconnected: '#4C566A',
            error: '#BF616A',
            default: '#4C566A',
        },
        permission: {
            default: '#4C566A',
            acceptEdits: '#81A1C1',
            bypass: '#D08770',
            plan: '#A3BE8C',
            readOnly: '#4C566A',
            safeYolo: '#D08770',
            yolo: '#BF616A',
        },
        permissionButton: {
            allow: { background: '#A3BE8C', text: '#2E3440' },
            deny: { background: '#BF616A', text: '#ECEFF4' },
            allowAll: { background: '#81A1C1', text: '#2E3440' },
            inactive: { background: '#3B4252', border: '#434C5E', text: '#4C566A' },
            selected: { background: '#434C5E', border: '#4C566A', text: '#ECEFF4' },
        },
        diff: {
            outline: '#434C5E',
            success: '#A3BE8C',
            error: '#BF616A',
            addedBg: '#1D3B2B',
            addedBorder: '#A3BE8C',
            addedText: '#D8DEE9',
            removedBg: '#3B2028',
            removedBorder: '#BF616A',
            removedText: '#D8DEE9',
            contextBg: '#2E3440',
            contextText: '#4C566A',
            lineNumberBg: '#2E3440',
            lineNumberText: '#4C566A',
            hunkHeaderBg: '#2E3440',
            hunkHeaderText: '#81A1C1',
            leadingSpaceDot: '#3B4252',
            inlineAddedBg: '#2E5A3E',
            inlineAddedText: '#A3BE8C',
            inlineRemovedBg: '#5A2E38',
            inlineRemovedText: '#D08770',
        },
        userMessageBackground: '#3B4252',
        userMessageText: '#ECEFF4',
        agentMessageText: '#ECEFF4',
        agentEventText: '#D8DEE9',
        syntaxKeyword: '#81A1C1',
        syntaxString: '#A3BE8C',
        syntaxComment: '#4C566A',
        syntaxNumber: '#B48EAD',
        syntaxFunction: '#88C0D0',
        syntaxBracket1: '#BF616A',
        syntaxBracket2: '#EBCB8B',
        syntaxBracket3: '#81A1C1',
        syntaxBracket4: '#D08770',
        syntaxBracket5: '#B48EAD',
        syntaxDefault: '#D8DEE9',
        gitBranchText: '#D8DEE9',
        gitFileCountText: '#D8DEE9',
        gitAddedText: '#A3BE8C',
        gitRemovedText: '#BF616A',
        terminal: {
            background: '#2E3440',
            prompt: '#A3BE8C',
            command: '#D8DEE9',
            stdout: '#D8DEE9',
            stderr: '#D08770',
            error: '#BF616A',
            emptyOutput: '#4C566A',
        },
    },
};
